import {
  AddPlanetToProject,
  ApplyStash,
  ConnectDB,
  CreateBranch,
  CreateProject,
  CreateTable,
  DeleteCurrentBranch,
  DeletePlanet,
  DeleteProject,
  DeleteSQLQuery,
  DeleteStash,
  DiscardChanges,
  DisconnectDB,
  DropTable,
  ExecuteSQLQuery,
  GenerateCode,
  GetActivePlanets,
  GetAllBranches,
  GetAllStashes,
  GetApex,
  GetCommitHistory,
  GetCurrentBranch,
  GetDevServersStatus,
  GetEnvVariable,
  GetGitStatus,
  GetPort,
  GetProjects,
  GetServerStatus,
  GetSQLHistory,
  GetTables,
  GetTableSchema,
  GitCommit,
  MergeBranch,
  OpenBrowser,
  OpenPlanetInVSCode,
  OpenProjectInVSCode,
  PickGenesisPath,
  RestartServer,
  RunBash,
  SaveApex,
  SaveEnvVariable,
  SaveSQLQuery,
  StartDevServer,
  StartServer,
  StashChanges,
  StopDevServer,
  StopServer,
  SwitchBranch,
  UpdatePort,
} from '../wailsjs/go/main/App'

export default class Go {
  static app = {
    openBrowser: OpenBrowser,
    env: {
      get: GetEnvVariable,
      set: SaveEnvVariable,
    },
  }
  static projects = {
    get: GetProjects,
    create: CreateProject,
    delete: DeleteProject,
    open: OpenProjectInVSCode,
    changeDir: PickGenesisPath,
  }
  static server = {
    start: StartServer,
    stop: StopServer,
    restartServer: RestartServer,
    status: GetServerStatus,
    getPort: GetPort,
    updatePort: UpdatePort,
  }
  static clients = {
    get: GetActivePlanets,
    create: AddPlanetToProject,
    delete: DeletePlanet,
    open: OpenPlanetInVSCode,
    bash: RunBash,
    startDev: StartDevServer,
    stopDev: StopDevServer,
    devServers: GetDevServersStatus,
  }
  static apex = {
    get: GetApex,
    save: SaveApex,
    generate: GenerateCode,
  }
  static db = {
    connect: ConnectDB,
    disconnect: DisconnectDB,
    tables: GetTables,
    createTable: CreateTable,
    getTablesCols: GetTableSchema,
    dropTable: DropTable,
    query: ExecuteSQLQuery,
  }
  static sqlEditor = {
    get: GetSQLHistory,
    save: SaveSQLQuery,
    del: DeleteSQLQuery,
  }
  static git = {
    status: GetGitStatus,
    commit: GitCommit,
    branch: GetCurrentBranch,
    branches: GetAllBranches,
    createBranch: CreateBranch,
    deleteBranch: DeleteCurrentBranch,
    switchBranch: SwitchBranch,
    mergeBranch: MergeBranch,
    commits: GetCommitHistory,
    discardChanges: DiscardChanges,
    stashes: GetAllStashes,
    stash: StashChanges,
    deleteStash: DeleteStash,
    applyStash: ApplyStash,
  }
}
