/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProjectsRouteLazyImport = createFileRoute('/projects')()
const LayoutRouteLazyImport = createFileRoute('/_layout')()
const LayoutIndexLazyImport = createFileRoute('/_layout/')()
const LayoutSettingsLazyImport = createFileRoute('/_layout/settings')()
const LayoutPackagesLazyImport = createFileRoute('/_layout/packages')()
const LayoutModulesLazyImport = createFileRoute('/_layout/modules')()
const ProjectsNameIndexLazyImport = createFileRoute('/projects/$name/')()
const ProjectsNameTablesLazyImport = createFileRoute('/projects/$name/tables')()
const ProjectsNameServerLazyImport = createFileRoute('/projects/$name/server')()
const ProjectsNameQueriesLazyImport = createFileRoute(
  '/projects/$name/queries',
)()
const ProjectsNameQ1LazyImport = createFileRoute('/projects/$name/q1')()
const ProjectsNameGpackLazyImport = createFileRoute('/projects/$name/gpack')()
const ProjectsNameGitLazyImport = createFileRoute('/projects/$name/git')()
const ProjectsNameDeployLazyImport = createFileRoute('/projects/$name/deploy')()
const ProjectsNameClientsLazyImport = createFileRoute(
  '/projects/$name/clients',
)()
const ProjectsNameAuthLazyImport = createFileRoute('/projects/$name/auth')()
const ProjectsNameApexLazyImport = createFileRoute('/projects/$name/apex')()

// Create/Update Routes

const ProjectsRouteLazyRoute = ProjectsRouteLazyImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/projects/route.lazy').then((d) => d.Route),
)

const LayoutRouteLazyRoute = LayoutRouteLazyImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_layout/route.lazy').then((d) => d.Route))

const LayoutIndexLazyRoute = LayoutIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteLazyRoute,
} as any).lazy(() => import('./routes/_layout/index.lazy').then((d) => d.Route))

const LayoutSettingsLazyRoute = LayoutSettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/_layout/settings.lazy').then((d) => d.Route),
)

const LayoutPackagesLazyRoute = LayoutPackagesLazyImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => LayoutRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/_layout/packages.lazy').then((d) => d.Route),
)

const LayoutModulesLazyRoute = LayoutModulesLazyImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => LayoutRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/_layout/modules.lazy').then((d) => d.Route),
)

const ProjectsNameIndexLazyRoute = ProjectsNameIndexLazyImport.update({
  id: '/$name/',
  path: '/$name/',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/index.lazy').then((d) => d.Route),
)

const ProjectsNameTablesLazyRoute = ProjectsNameTablesLazyImport.update({
  id: '/$name/tables',
  path: '/$name/tables',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/tables.lazy').then((d) => d.Route),
)

const ProjectsNameServerLazyRoute = ProjectsNameServerLazyImport.update({
  id: '/$name/server',
  path: '/$name/server',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/server.lazy').then((d) => d.Route),
)

const ProjectsNameQueriesLazyRoute = ProjectsNameQueriesLazyImport.update({
  id: '/$name/queries',
  path: '/$name/queries',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/queries.lazy').then((d) => d.Route),
)

const ProjectsNameQ1LazyRoute = ProjectsNameQ1LazyImport.update({
  id: '/$name/q1',
  path: '/$name/q1',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/q1.lazy').then((d) => d.Route),
)

const ProjectsNameGpackLazyRoute = ProjectsNameGpackLazyImport.update({
  id: '/$name/gpack',
  path: '/$name/gpack',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/gpack.lazy').then((d) => d.Route),
)

const ProjectsNameGitLazyRoute = ProjectsNameGitLazyImport.update({
  id: '/$name/git',
  path: '/$name/git',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/git.lazy').then((d) => d.Route),
)

const ProjectsNameDeployLazyRoute = ProjectsNameDeployLazyImport.update({
  id: '/$name/deploy',
  path: '/$name/deploy',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/deploy.lazy').then((d) => d.Route),
)

const ProjectsNameClientsLazyRoute = ProjectsNameClientsLazyImport.update({
  id: '/$name/clients',
  path: '/$name/clients',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/clients.lazy').then((d) => d.Route),
)

const ProjectsNameAuthLazyRoute = ProjectsNameAuthLazyImport.update({
  id: '/$name/auth',
  path: '/$name/auth',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/auth.lazy').then((d) => d.Route),
)

const ProjectsNameApexLazyRoute = ProjectsNameApexLazyImport.update({
  id: '/$name/apex',
  path: '/$name/apex',
  getParentRoute: () => ProjectsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/$name/apex.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout/modules': {
      id: '/_layout/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof LayoutModulesLazyImport
      parentRoute: typeof LayoutRouteLazyImport
    }
    '/_layout/packages': {
      id: '/_layout/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof LayoutPackagesLazyImport
      parentRoute: typeof LayoutRouteLazyImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsLazyImport
      parentRoute: typeof LayoutRouteLazyImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexLazyImport
      parentRoute: typeof LayoutRouteLazyImport
    }
    '/projects/$name/apex': {
      id: '/projects/$name/apex'
      path: '/$name/apex'
      fullPath: '/projects/$name/apex'
      preLoaderRoute: typeof ProjectsNameApexLazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
    '/projects/$name/auth': {
      id: '/projects/$name/auth'
      path: '/$name/auth'
      fullPath: '/projects/$name/auth'
      preLoaderRoute: typeof ProjectsNameAuthLazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
    '/projects/$name/clients': {
      id: '/projects/$name/clients'
      path: '/$name/clients'
      fullPath: '/projects/$name/clients'
      preLoaderRoute: typeof ProjectsNameClientsLazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
    '/projects/$name/deploy': {
      id: '/projects/$name/deploy'
      path: '/$name/deploy'
      fullPath: '/projects/$name/deploy'
      preLoaderRoute: typeof ProjectsNameDeployLazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
    '/projects/$name/git': {
      id: '/projects/$name/git'
      path: '/$name/git'
      fullPath: '/projects/$name/git'
      preLoaderRoute: typeof ProjectsNameGitLazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
    '/projects/$name/gpack': {
      id: '/projects/$name/gpack'
      path: '/$name/gpack'
      fullPath: '/projects/$name/gpack'
      preLoaderRoute: typeof ProjectsNameGpackLazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
    '/projects/$name/q1': {
      id: '/projects/$name/q1'
      path: '/$name/q1'
      fullPath: '/projects/$name/q1'
      preLoaderRoute: typeof ProjectsNameQ1LazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
    '/projects/$name/queries': {
      id: '/projects/$name/queries'
      path: '/$name/queries'
      fullPath: '/projects/$name/queries'
      preLoaderRoute: typeof ProjectsNameQueriesLazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
    '/projects/$name/server': {
      id: '/projects/$name/server'
      path: '/$name/server'
      fullPath: '/projects/$name/server'
      preLoaderRoute: typeof ProjectsNameServerLazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
    '/projects/$name/tables': {
      id: '/projects/$name/tables'
      path: '/$name/tables'
      fullPath: '/projects/$name/tables'
      preLoaderRoute: typeof ProjectsNameTablesLazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
    '/projects/$name/': {
      id: '/projects/$name/'
      path: '/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof ProjectsNameIndexLazyImport
      parentRoute: typeof ProjectsRouteLazyImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteLazyRouteChildren {
  LayoutModulesLazyRoute: typeof LayoutModulesLazyRoute
  LayoutPackagesLazyRoute: typeof LayoutPackagesLazyRoute
  LayoutSettingsLazyRoute: typeof LayoutSettingsLazyRoute
  LayoutIndexLazyRoute: typeof LayoutIndexLazyRoute
}

const LayoutRouteLazyRouteChildren: LayoutRouteLazyRouteChildren = {
  LayoutModulesLazyRoute: LayoutModulesLazyRoute,
  LayoutPackagesLazyRoute: LayoutPackagesLazyRoute,
  LayoutSettingsLazyRoute: LayoutSettingsLazyRoute,
  LayoutIndexLazyRoute: LayoutIndexLazyRoute,
}

const LayoutRouteLazyRouteWithChildren = LayoutRouteLazyRoute._addFileChildren(
  LayoutRouteLazyRouteChildren,
)

interface ProjectsRouteLazyRouteChildren {
  ProjectsNameApexLazyRoute: typeof ProjectsNameApexLazyRoute
  ProjectsNameAuthLazyRoute: typeof ProjectsNameAuthLazyRoute
  ProjectsNameClientsLazyRoute: typeof ProjectsNameClientsLazyRoute
  ProjectsNameDeployLazyRoute: typeof ProjectsNameDeployLazyRoute
  ProjectsNameGitLazyRoute: typeof ProjectsNameGitLazyRoute
  ProjectsNameGpackLazyRoute: typeof ProjectsNameGpackLazyRoute
  ProjectsNameQ1LazyRoute: typeof ProjectsNameQ1LazyRoute
  ProjectsNameQueriesLazyRoute: typeof ProjectsNameQueriesLazyRoute
  ProjectsNameServerLazyRoute: typeof ProjectsNameServerLazyRoute
  ProjectsNameTablesLazyRoute: typeof ProjectsNameTablesLazyRoute
  ProjectsNameIndexLazyRoute: typeof ProjectsNameIndexLazyRoute
}

const ProjectsRouteLazyRouteChildren: ProjectsRouteLazyRouteChildren = {
  ProjectsNameApexLazyRoute: ProjectsNameApexLazyRoute,
  ProjectsNameAuthLazyRoute: ProjectsNameAuthLazyRoute,
  ProjectsNameClientsLazyRoute: ProjectsNameClientsLazyRoute,
  ProjectsNameDeployLazyRoute: ProjectsNameDeployLazyRoute,
  ProjectsNameGitLazyRoute: ProjectsNameGitLazyRoute,
  ProjectsNameGpackLazyRoute: ProjectsNameGpackLazyRoute,
  ProjectsNameQ1LazyRoute: ProjectsNameQ1LazyRoute,
  ProjectsNameQueriesLazyRoute: ProjectsNameQueriesLazyRoute,
  ProjectsNameServerLazyRoute: ProjectsNameServerLazyRoute,
  ProjectsNameTablesLazyRoute: ProjectsNameTablesLazyRoute,
  ProjectsNameIndexLazyRoute: ProjectsNameIndexLazyRoute,
}

const ProjectsRouteLazyRouteWithChildren =
  ProjectsRouteLazyRoute._addFileChildren(ProjectsRouteLazyRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteLazyRouteWithChildren
  '/projects': typeof ProjectsRouteLazyRouteWithChildren
  '/modules': typeof LayoutModulesLazyRoute
  '/packages': typeof LayoutPackagesLazyRoute
  '/settings': typeof LayoutSettingsLazyRoute
  '/': typeof LayoutIndexLazyRoute
  '/projects/$name/apex': typeof ProjectsNameApexLazyRoute
  '/projects/$name/auth': typeof ProjectsNameAuthLazyRoute
  '/projects/$name/clients': typeof ProjectsNameClientsLazyRoute
  '/projects/$name/deploy': typeof ProjectsNameDeployLazyRoute
  '/projects/$name/git': typeof ProjectsNameGitLazyRoute
  '/projects/$name/gpack': typeof ProjectsNameGpackLazyRoute
  '/projects/$name/q1': typeof ProjectsNameQ1LazyRoute
  '/projects/$name/queries': typeof ProjectsNameQueriesLazyRoute
  '/projects/$name/server': typeof ProjectsNameServerLazyRoute
  '/projects/$name/tables': typeof ProjectsNameTablesLazyRoute
  '/projects/$name': typeof ProjectsNameIndexLazyRoute
}

export interface FileRoutesByTo {
  '/projects': typeof ProjectsRouteLazyRouteWithChildren
  '/modules': typeof LayoutModulesLazyRoute
  '/packages': typeof LayoutPackagesLazyRoute
  '/settings': typeof LayoutSettingsLazyRoute
  '/': typeof LayoutIndexLazyRoute
  '/projects/$name/apex': typeof ProjectsNameApexLazyRoute
  '/projects/$name/auth': typeof ProjectsNameAuthLazyRoute
  '/projects/$name/clients': typeof ProjectsNameClientsLazyRoute
  '/projects/$name/deploy': typeof ProjectsNameDeployLazyRoute
  '/projects/$name/git': typeof ProjectsNameGitLazyRoute
  '/projects/$name/gpack': typeof ProjectsNameGpackLazyRoute
  '/projects/$name/q1': typeof ProjectsNameQ1LazyRoute
  '/projects/$name/queries': typeof ProjectsNameQueriesLazyRoute
  '/projects/$name/server': typeof ProjectsNameServerLazyRoute
  '/projects/$name/tables': typeof ProjectsNameTablesLazyRoute
  '/projects/$name': typeof ProjectsNameIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteLazyRouteWithChildren
  '/projects': typeof ProjectsRouteLazyRouteWithChildren
  '/_layout/modules': typeof LayoutModulesLazyRoute
  '/_layout/packages': typeof LayoutPackagesLazyRoute
  '/_layout/settings': typeof LayoutSettingsLazyRoute
  '/_layout/': typeof LayoutIndexLazyRoute
  '/projects/$name/apex': typeof ProjectsNameApexLazyRoute
  '/projects/$name/auth': typeof ProjectsNameAuthLazyRoute
  '/projects/$name/clients': typeof ProjectsNameClientsLazyRoute
  '/projects/$name/deploy': typeof ProjectsNameDeployLazyRoute
  '/projects/$name/git': typeof ProjectsNameGitLazyRoute
  '/projects/$name/gpack': typeof ProjectsNameGpackLazyRoute
  '/projects/$name/q1': typeof ProjectsNameQ1LazyRoute
  '/projects/$name/queries': typeof ProjectsNameQueriesLazyRoute
  '/projects/$name/server': typeof ProjectsNameServerLazyRoute
  '/projects/$name/tables': typeof ProjectsNameTablesLazyRoute
  '/projects/$name/': typeof ProjectsNameIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/projects'
    | '/modules'
    | '/packages'
    | '/settings'
    | '/'
    | '/projects/$name/apex'
    | '/projects/$name/auth'
    | '/projects/$name/clients'
    | '/projects/$name/deploy'
    | '/projects/$name/git'
    | '/projects/$name/gpack'
    | '/projects/$name/q1'
    | '/projects/$name/queries'
    | '/projects/$name/server'
    | '/projects/$name/tables'
    | '/projects/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/projects'
    | '/modules'
    | '/packages'
    | '/settings'
    | '/'
    | '/projects/$name/apex'
    | '/projects/$name/auth'
    | '/projects/$name/clients'
    | '/projects/$name/deploy'
    | '/projects/$name/git'
    | '/projects/$name/gpack'
    | '/projects/$name/q1'
    | '/projects/$name/queries'
    | '/projects/$name/server'
    | '/projects/$name/tables'
    | '/projects/$name'
  id:
    | '__root__'
    | '/_layout'
    | '/projects'
    | '/_layout/modules'
    | '/_layout/packages'
    | '/_layout/settings'
    | '/_layout/'
    | '/projects/$name/apex'
    | '/projects/$name/auth'
    | '/projects/$name/clients'
    | '/projects/$name/deploy'
    | '/projects/$name/git'
    | '/projects/$name/gpack'
    | '/projects/$name/q1'
    | '/projects/$name/queries'
    | '/projects/$name/server'
    | '/projects/$name/tables'
    | '/projects/$name/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRouteLazyRoute: typeof LayoutRouteLazyRouteWithChildren
  ProjectsRouteLazyRoute: typeof ProjectsRouteLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteLazyRoute: LayoutRouteLazyRouteWithChildren,
  ProjectsRouteLazyRoute: ProjectsRouteLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/projects"
      ]
    },
    "/_layout": {
      "filePath": "_layout/route.lazy.tsx",
      "children": [
        "/_layout/modules",
        "/_layout/packages",
        "/_layout/settings",
        "/_layout/"
      ]
    },
    "/projects": {
      "filePath": "projects/route.lazy.tsx",
      "children": [
        "/projects/$name/apex",
        "/projects/$name/auth",
        "/projects/$name/clients",
        "/projects/$name/deploy",
        "/projects/$name/git",
        "/projects/$name/gpack",
        "/projects/$name/q1",
        "/projects/$name/queries",
        "/projects/$name/server",
        "/projects/$name/tables",
        "/projects/$name/"
      ]
    },
    "/_layout/modules": {
      "filePath": "_layout/modules.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/packages": {
      "filePath": "_layout/packages.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/settings": {
      "filePath": "_layout/settings.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.lazy.tsx",
      "parent": "/_layout"
    },
    "/projects/$name/apex": {
      "filePath": "projects/$name/apex.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/$name/auth": {
      "filePath": "projects/$name/auth.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/$name/clients": {
      "filePath": "projects/$name/clients.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/$name/deploy": {
      "filePath": "projects/$name/deploy.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/$name/git": {
      "filePath": "projects/$name/git.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/$name/gpack": {
      "filePath": "projects/$name/gpack.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/$name/q1": {
      "filePath": "projects/$name/q1.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/$name/queries": {
      "filePath": "projects/$name/queries.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/$name/server": {
      "filePath": "projects/$name/server.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/$name/tables": {
      "filePath": "projects/$name/tables.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/$name/": {
      "filePath": "projects/$name/index.lazy.tsx",
      "parent": "/projects"
    }
  }
}
ROUTE_MANIFEST_END */
