// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProject(arg1:main.NewProjectOptions):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetProjects():Promise<Array<main.ProjectInfo>>;
