// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlanetToProject(arg1, arg2) {
  return window['go']['main']['App']['AddPlanetToProject'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeletePlanet(arg1, arg2) {
  return window['go']['main']['App']['DeletePlanet'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetActivePlanets(arg1) {
  return window['go']['main']['App']['GetActivePlanets'](arg1);
}

export function GetApex(arg1) {
  return window['go']['main']['App']['GetApex'](arg1);
}

export function GetDevServersStatus(arg1) {
  return window['go']['main']['App']['GetDevServersStatus'](arg1);
}

export function GetPort(arg1) {
  return window['go']['main']['App']['GetPort'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function OpenPlanetInVSCode(arg1, arg2) {
  return window['go']['main']['App']['OpenPlanetInVSCode'](arg1, arg2);
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function RunBash(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunBash'](arg1, arg2, arg3);
}

export function SaveApex(arg1, arg2) {
  return window['go']['main']['App']['SaveApex'](arg1, arg2);
}

export function StartDevServer(arg1, arg2) {
  return window['go']['main']['App']['StartDevServer'](arg1, arg2);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopDevServer(arg1, arg2) {
  return window['go']['main']['App']['StopDevServer'](arg1, arg2);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function UpdatePort(arg1, arg2) {
  return window['go']['main']['App']['UpdatePort'](arg1, arg2);
}
