// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlanetToProject(arg1, arg2) {
  return window['go']['main']['App']['AddPlanetToProject'](arg1, arg2);
}

export function ConnectDB(arg1) {
  return window['go']['main']['App']['ConnectDB'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTable'](arg1, arg2, arg3);
}

export function DeletePlanet(arg1, arg2) {
  return window['go']['main']['App']['DeletePlanet'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSQLQuery(arg1, arg2) {
  return window['go']['main']['App']['DeleteSQLQuery'](arg1, arg2);
}

export function DisconnectDB() {
  return window['go']['main']['App']['DisconnectDB']();
}

export function DropTable(arg1, arg2) {
  return window['go']['main']['App']['DropTable'](arg1, arg2);
}

export function ExecuteSQLQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteSQLQuery'](arg1, arg2);
}

export function GenerateCode(arg1) {
  return window['go']['main']['App']['GenerateCode'](arg1);
}

export function GetActivePlanets(arg1) {
  return window['go']['main']['App']['GetActivePlanets'](arg1);
}

export function GetApex(arg1) {
  return window['go']['main']['App']['GetApex'](arg1);
}

export function GetDSN(arg1) {
  return window['go']['main']['App']['GetDSN'](arg1);
}

export function GetDevServersStatus(arg1) {
  return window['go']['main']['App']['GetDevServersStatus'](arg1);
}

export function GetEnvVariable(arg1) {
  return window['go']['main']['App']['GetEnvVariable'](arg1);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetPort(arg1) {
  return window['go']['main']['App']['GetPort'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSQLHistory(arg1) {
  return window['go']['main']['App']['GetSQLHistory'](arg1);
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function GetTableSchema(arg1, arg2) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2);
}

export function GetTables(arg1) {
  return window['go']['main']['App']['GetTables'](arg1);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function InitGitRepo(arg1) {
  return window['go']['main']['App']['InitGitRepo'](arg1);
}

export function LoadEnv() {
  return window['go']['main']['App']['LoadEnv']();
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function OpenPlanetInVSCode(arg1, arg2) {
  return window['go']['main']['App']['OpenPlanetInVSCode'](arg1, arg2);
}

export function OpenProjectInVSCode(arg1) {
  return window['go']['main']['App']['OpenProjectInVSCode'](arg1);
}

export function PickGenesisPath() {
  return window['go']['main']['App']['PickGenesisPath']();
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function RunBash(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunBash'](arg1, arg2, arg3);
}

export function SaveApex(arg1, arg2) {
  return window['go']['main']['App']['SaveApex'](arg1, arg2);
}

export function SaveEnvVariable(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvVariable'](arg1, arg2);
}

export function SaveSQLQuery(arg1, arg2) {
  return window['go']['main']['App']['SaveSQLQuery'](arg1, arg2);
}

export function StartDevServer(arg1, arg2) {
  return window['go']['main']['App']['StartDevServer'](arg1, arg2);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopDevServer(arg1, arg2) {
  return window['go']['main']['App']['StopDevServer'](arg1, arg2);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function UpdatePort(arg1, arg2) {
  return window['go']['main']['App']['UpdatePort'](arg1, arg2);
}
